title:              Blog
tagline:            on GitHub Pages
description:        Content-focused template for a blog hosted on GitHub Pages.
url:                http://greentec.github.io

author:
  name:             Hwanhee, Kim
  url:              https://twitter.com/greentecq
  email:            greentec91@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            'http://greentec.github.io/texts.github.io'
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         'http://greentec.github.io/texts.github.io'
    values:
      layout:       post
source: '/texts.github.io'
