title:              Greentec's Blog
tagline:            on GitHub Pages
description:        Game Designer
url:                http://greentec.github.io

author:
  name:             greentec
  url:              https://twitter.com/greentecq
  email:            greentec91@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
