title:              greentec's blog
tagline:            game designer, scripter, researcher
description:        greentec's blog (@greentecq)
url:                http://greentec.github.io

author:
  name:             greentec
  url:              https://twitter.com/greentecq
  email:            greentec91@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           999
paginate-path:      "/page:lang/page:num/"
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post

plugins:
    - jekyll-feed
